- name: copy pssh and crmsh
  copy: src={{ item }} dest=/tmp/
  with_items:
  - pssh-2.3.1-2.el6.x86_64.rpm
  - crmsh-1.2.6-4.el6.x86_64.rpm
- name: install pssh and crmsh
  yum: name={{ item }} state=present
  with_items:
  - /tmp/pssh-2.3.1-2.el6.x86_64.rpm
  - /tmp/crmsh-1.2.6-4.el6.x86_64.rpm
