apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true                       # 使用宿主机网络
      dnsPolicy: ClusterFirstWithHostNet      # 当hostNetwork为True时Pod默认使用所在宿主机的DNS，因此这里需要做调整
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

