SELECT
     LG_ID, CNTMNG_ID, INTF_NM, REQST_CLTPT_ID, REQST_MODE_CODE, INTF_REQST_PARA_CNTT, INTF_RSP_CNTT, RSP_CODE, RSP_CNTT, OP_STAFF_ID, DATE_FORMAT(CRT_TIME,'%Y-%m-%d %H:%i:%s') as CRT_TIME, MOBNUM, BIZ_OP_TOTAL_TMLEN_VAL, DATE_FORMAT(CMOS_MODIFY_TIME,'%Y-%m-%d %H:%i:%s') as CMOS_MODIFY_TIME 
FROM 
    t_log_interfacelog_201802
WHERE
    CRT_TIME > :sql_last_value

